services:
  fluig_dashboard:
    container_name: fluig_dashboard
    build:
      dockerfile: Dockerfile
    command: ["npm", "start"]
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          ignore:
            - node_modules/
    ports: 
      - "4200:4200"
    volumes:
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules: